/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Organization {
  'id' : string,
  'ownerId' : Principal,
  'stripeSubscriptionId' : [] | [string],
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'isActive' : boolean,
  'logoUrl' : [] | [string],
  'stripeCustomerId' : [] | [string],
  'supportedLanguages' : Array<string>,
  'planTier' : PlanTier,
  'primaryLanguage' : string,
}
export interface OrganizationInput {
  'ownerId' : Principal,
  'name' : string,
  'description' : string,
  'planTier' : PlanTier,
  'primaryLanguage' : string,
}
export interface Lead {
  'id' : string,
  'name' : string,
  'email' : string,
  'interest' : string,
  'orgName' : [] | [string],
  'preferredLanguage' : string,
  'createdAt' : bigint,
  'source' : string,
}
export interface LeadInput {
  'name' : string,
  'email' : string,
  'interest' : string,
  'orgName' : [] | [string],
  'preferredLanguage' : string,
  'source' : string,
}
export type PlanTier = { 'enterprise' : null } |
  { 'starter' : null } |
  { 'free' : null } |
  { 'professional' : null };
export type Principal = Principal;
export type Role = { 'super_admin' : null } |
  { 'org_admin' : null } |
  { 'end_customer' : null } |
  { 'team_member' : null };
export interface User {
  'principal' : Principal,
  'preferredLanguage' : string,
  'displayName' : string,
  'orgId' : [] | [string],
  'lastLoginAt' : [] | [bigint],
  'createdAt' : bigint,
  'role' : Role,
  'isActive' : boolean,
  'email' : string,
  'stripeCustomerId' : [] | [string],
  'avatarUrl' : [] | [string],
  'branchId' : [] | [string],
}
export interface UserInput {
  'principal' : Principal,
  'preferredLanguage' : string,
  'displayName' : string,
  'email' : string,
}
export interface InviteLink {
  'id' : string,
  'code' : string,
  'orgId' : [] | [string],
  'createdBy' : Principal,
  'role' : Role,
  'maxRedemptions' : [] | [bigint],
  'redemptionCount' : bigint,
  'expiresAt' : [] | [bigint],
  'isActive' : boolean,
  'createdAt' : bigint,
}
export interface CreateInviteLinkInput {
  'role' : Role,
  'maxRedemptions' : [] | [bigint],
  'expiresAt' : [] | [bigint],
  'orgId' : [] | [string],
}
export interface _SERVICE {
  'createOrganization' : ActorMethod<
    [OrganizationInput],
    { 'ok' : Organization } |
      { 'err' : string }
  >,
  'getAllOrganizations' : ActorMethod<[], Array<Organization>>,
  'getAllUsers' : ActorMethod<[], Array<User>>,
  'getAllUsersByEmail' : ActorMethod<[], Array<User>>,
  'getMyOrganization' : ActorMethod<[], [] | [Organization]>,
  'getMyProfile' : ActorMethod<[], User>,
  'getOrganizationById' : ActorMethod<[string], [] | [Organization]>,
  'getUserById' : ActorMethod<[Principal], User>,
  'isRegistered' : ActorMethod<[], boolean>,
  'registerUser' : ActorMethod<
    [UserInput],
    { 'ok' : User } |
      { 'err' : string }
  >,
  'updateMyProfile' : ActorMethod<
    [{ displayName: string; email: string; preferredLanguage: string; avatarUrl: [] | [string] }],
    { 'ok' : User } | { 'err' : string }
  >,
  'updateLastLogin' : ActorMethod<[], undefined>,
  'submitLead' : ActorMethod<
    [LeadInput],
    { 'ok' : Lead } | { 'err' : string }
  >,
  'getAllLeads' : ActorMethod<
    [],
    { 'ok' : Array<Lead> } | { 'err' : string }
  >,
  'createInviteLink' : ActorMethod<
    [CreateInviteLinkInput],
    { 'ok' : InviteLink } | { 'err' : string }
  >,
  'getAllInviteLinks' : ActorMethod<[], Array<InviteLink>>,
  'getMyInviteLinks' : ActorMethod<[], Array<InviteLink>>,
  'getInviteLinkByCode' : ActorMethod<
    [string],
    { 'ok' : InviteLink } | { 'err' : string }
  >,
  'redeemInviteLink' : ActorMethod<
    [string, UserInput],
    { 'ok' : User } | { 'err' : string }
  >,
  'deactivateInviteLink' : ActorMethod<
    [string],
    { 'ok' : InviteLink } | { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];