/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Principal = IDL.Principal;
export const PlanTier = IDL.Variant({
  'enterprise' : IDL.Null,
  'starter' : IDL.Null,
  'free' : IDL.Null,
  'professional' : IDL.Null,
});
export const OrganizationInput = IDL.Record({
  'ownerId' : Principal,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'planTier' : PlanTier,
  'primaryLanguage' : IDL.Text,
});
export const Organization = IDL.Record({
  'id' : IDL.Text,
  'ownerId' : Principal,
  'stripeSubscriptionId' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'logoUrl' : IDL.Opt(IDL.Text),
  'stripeCustomerId' : IDL.Opt(IDL.Text),
  'supportedLanguages' : IDL.Vec(IDL.Text),
  'planTier' : PlanTier,
  'primaryLanguage' : IDL.Text,
});
export const Role = IDL.Variant({
  'super_admin' : IDL.Null,
  'org_admin' : IDL.Null,
  'end_customer' : IDL.Null,
  'team_member' : IDL.Null,
});
export const User = IDL.Record({
  'principal' : Principal,
  'preferredLanguage' : IDL.Text,
  'displayName' : IDL.Text,
  'orgId' : IDL.Opt(IDL.Text),
  'lastLoginAt' : IDL.Opt(IDL.Int),
  'createdAt' : IDL.Int,
  'role' : IDL.Role,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'stripeCustomerId' : IDL.Opt(IDL.Text),
  'avatarUrl' : IDL.Opt(IDL.Text),
  'branchId' : IDL.Opt(IDL.Text),
});
export const UserInput = IDL.Record({
  'principal' : Principal,
  'preferredLanguage' : IDL.Text,
  'displayName' : IDL.Text,
  'email' : IDL.Text,
});
export const Lead = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'interest' : IDL.Text,
  'orgName' : IDL.Opt(IDL.Text),
  'preferredLanguage' : IDL.Text,
  'createdAt' : IDL.Int,
  'source' : IDL.Text,
});
export const LeadInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'interest' : IDL.Text,
  'orgName' : IDL.Opt(IDL.Text),
  'preferredLanguage' : IDL.Text,
  'source' : IDL.Text,
});
export const InviteLink = IDL.Record({
  'id' : IDL.Text,
  'code' : IDL.Text,
  'orgId' : IDL.Opt(IDL.Text),
  'createdBy' : Principal,
  'role' : Role,
  'maxRedemptions' : IDL.Opt(IDL.Nat),
  'redemptionCount' : IDL.Nat,
  'expiresAt' : IDL.Opt(IDL.Int),
  'isActive' : IDL.Bool,
  'createdAt' : IDL.Int,
});
export const CreateInviteLinkInput = IDL.Record({
  'role' : Role,
  'maxRedemptions' : IDL.Opt(IDL.Nat),
  'expiresAt' : IDL.Opt(IDL.Int),
  'orgId' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'createOrganization' : IDL.Func(
      [OrganizationInput],
      [IDL.Variant({ 'ok' : Organization, 'err' : IDL.Text })],
      [],
    ),
  'getAllOrganizations' : IDL.Func([], [IDL.Vec(Organization)], []),
  'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getAllUsersByEmail' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getMyOrganization' : IDL.Func([], [IDL.Opt(Organization)], []),
  'getMyProfile' : IDL.Func([], [User], []),
  'getOrganizationById' : IDL.Func([IDL.Text], [IDL.Opt(Organization)], []),
  'getUserById' : IDL.Func([Principal], [User], []),
  'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUser' : IDL.Func(
      [UserInput],
      [IDL.Variant({ 'ok' : User, 'err' : IDL.Text })],
      [],
    ),
  'updateMyProfile' : IDL.Func(
      [IDL.Record({ displayName: IDL.Text, email: IDL.Text, preferredLanguage: IDL.Text, avatarUrl: IDL.Opt(IDL.Text) })],
      [IDL.Variant({ 'ok' : User, 'err' : IDL.Text })],
      [],
    ),
  'updateLastLogin' : IDL.Func([], [], []),
  'submitLead' : IDL.Func(
      [LeadInput],
      [IDL.Variant({ 'ok' : Lead, 'err' : IDL.Text })],
      [],
    ),
  'getAllLeads' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : IDL.Vec(Lead), 'err' : IDL.Text })],
      [],
    ),
  'createInviteLink' : IDL.Func(
      [CreateInviteLinkInput],
      [IDL.Variant({ 'ok' : InviteLink, 'err' : IDL.Text })],
      [],
    ),
  'getAllInviteLinks' : IDL.Func([], [IDL.Vec(InviteLink)], ['query']),
  'getMyInviteLinks' : IDL.Func([], [IDL.Vec(InviteLink)], ['query']),
  'getInviteLinkByCode' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : InviteLink, 'err' : IDL.Text })],
      ['query'],
    ),
  'redeemInviteLink' : IDL.Func(
      [IDL.Text, UserInput],
      [IDL.Variant({ 'ok' : User, 'err' : IDL.Text })],
      [],
    ),
  'deactivateInviteLink' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : InviteLink, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Principal = IDL.Principal;
  const PlanTier = IDL.Variant({
    'enterprise' : IDL.Null,
    'starter' : IDL.Null,
    'free' : IDL.Null,
    'professional' : IDL.Null,
  });
  const OrganizationInput = IDL.Record({
    'ownerId' : Principal,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'planTier' : PlanTier,
    'primaryLanguage' : IDL.Text,
  });
  const Organization = IDL.Record({
    'id' : IDL.Text,
    'ownerId' : Principal,
    'stripeSubscriptionId' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'logoUrl' : IDL.Opt(IDL.Text),
    'stripeCustomerId' : IDL.Opt(IDL.Text),
    'supportedLanguages' : IDL.Vec(IDL.Text),
    'planTier' : PlanTier,
    'primaryLanguage' : IDL.Text,
  });
  const Role = IDL.Variant({
    'super_admin' : IDL.Null,
    'org_admin' : IDL.Null,
    'end_customer' : IDL.Null,
    'team_member' : IDL.Null,
  });
  const User = IDL.Record({
    'principal' : Principal,
    'preferredLanguage' : IDL.Text,
    'displayName' : IDL.Text,
    'orgId' : IDL.Opt(IDL.Text),
    'lastLoginAt' : IDL.Opt(IDL.Int),
    'createdAt' : IDL.Int,
    'role' : Role,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'stripeCustomerId' : IDL.Opt(IDL.Text),
    'avatarUrl' : IDL.Opt(IDL.Text),
    'branchId' : IDL.Opt(IDL.Text),
  });
  const UserInput = IDL.Record({
    'principal' : Principal,
    'preferredLanguage' : IDL.Text,
    'displayName' : IDL.Text,
    'email' : IDL.Text,
  });
  const Lead = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'interest' : IDL.Text,
    'orgName' : IDL.Opt(IDL.Text),
    'preferredLanguage' : IDL.Text,
    'createdAt' : IDL.Int,
    'source' : IDL.Text,
  });
  const LeadInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'interest' : IDL.Text,
    'orgName' : IDL.Opt(IDL.Text),
    'preferredLanguage' : IDL.Text,
    'source' : IDL.Text,
  });
  const InviteLink = IDL.Record({
    'id' : IDL.Text,
    'code' : IDL.Text,
    'orgId' : IDL.Opt(IDL.Text),
    'createdBy' : Principal,
    'role' : Role,
    'maxRedemptions' : IDL.Opt(IDL.Nat),
    'redemptionCount' : IDL.Nat,
    'expiresAt' : IDL.Opt(IDL.Int),
    'isActive' : IDL.Bool,
    'createdAt' : IDL.Int,
  });
  const CreateInviteLinkInput = IDL.Record({
    'role' : Role,
    'maxRedemptions' : IDL.Opt(IDL.Nat),
    'expiresAt' : IDL.Opt(IDL.Int),
    'orgId' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'createOrganization' : IDL.Func(
        [OrganizationInput],
        [IDL.Variant({ 'ok' : Organization, 'err' : IDL.Text })],
        [],
      ),
    'getAllOrganizations' : IDL.Func([], [IDL.Vec(Organization)], []),
    'getAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getAllUsersByEmail' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getMyOrganization' : IDL.Func([], [IDL.Opt(Organization)], []),
    'getMyProfile' : IDL.Func([], [User], []),
    'getOrganizationById' : IDL.Func([IDL.Text], [IDL.Opt(Organization)], []),
    'getUserById' : IDL.Func([Principal], [User], []),
    'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUser' : IDL.Func(
        [UserInput],
        [IDL.Variant({ 'ok' : User, 'err' : IDL.Text })],
        [],
      ),
    'updateMyProfile' : IDL.Func(
        [IDL.Record({ displayName: IDL.Text, email: IDL.Text, preferredLanguage: IDL.Text, avatarUrl: IDL.Opt(IDL.Text) })],
        [IDL.Variant({ 'ok' : User, 'err' : IDL.Text })],
        [],
      ),
    'updateLastLogin' : IDL.Func([], [], []),
    'submitLead' : IDL.Func(
        [LeadInput],
        [IDL.Variant({ 'ok' : Lead, 'err' : IDL.Text })],
        [],
      ),
    'getAllLeads' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : IDL.Vec(Lead), 'err' : IDL.Text })],
        [],
      ),
    'createInviteLink' : IDL.Func(
        [CreateInviteLinkInput],
        [IDL.Variant({ 'ok' : InviteLink, 'err' : IDL.Text })],
        [],
      ),
    'getAllInviteLinks' : IDL.Func([], [IDL.Vec(InviteLink)], ['query']),
    'getMyInviteLinks' : IDL.Func([], [IDL.Vec(InviteLink)], ['query']),
    'getInviteLinkByCode' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : InviteLink, 'err' : IDL.Text })],
        ['query'],
      ),
    'redeemInviteLink' : IDL.Func(
        [IDL.Text, UserInput],
        [IDL.Variant({ 'ok' : User, 'err' : IDL.Text })],
        [],
      ),
    'deactivateInviteLink' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : InviteLink, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };